easy_admin:
    disabled_actions: ['show']
    site_name: '<h1 style="font-family: Noto Serif, serif; color: #FFF;" >NewGenerationSupreme</h1>'
    formats:
      datetime: 'd/m/Y'
    design:
      form_theme:
        - '@EasyAdmin/form/bootstrap_4.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
      assets:
        css:
          - 'assets/css/admin.css'

      menu:
        - {entity: 'News', icon: 'info'}
        - {entity: 'Banner', icon: 'images'}
        - {entity: 'Category', icon: 'book'}
        - {entity: 'SubCategory', icon: 'book-open'}
        - {entity: 'SubCategory2', icon: 'book-open'}
        - {entity: 'Order', icon: 'calendar-alt'}
        - {entity: 'Product', icon: 'sitemap'}
        - {entity: 'Size', icon: 'sitemap'}
        - {entity: 'Stock', icon: 'box'}
        - {entity: 'ShippingMethod', icon: 'truck'}
        - {entity: 'Tag', icon: 'tags'}
        - {entity: 'User', icon: 'users'}

    entities:
      News:
        class: App\Entity\News
        list:
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}

      Banner:
        class: App\Entity\Banner
        list:
          fields:
            - id
            - { property: 'image', type: 'image', base_path: '%uploads_path%' }
            - title
            - description
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        show:
          fields:
            - { property: 'image', type: 'image', base_path: '%uploads_path%' }
        form:
          fields:
            - { property: 'imageFile', type: 'vich_image' }
            - title
            - { property: 'description', type: 'fos_ckeditor'}

      Category:
        class: App\Entity\Category
        list:
          fields:
            - id
            - name
            - { property: 'image', type: 'image', base_path: '%uploads_path%'}
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        show:
          fields:
            - { property: 'image', type: 'image', base_path: '%uploads_path%' }
        form:
          fields:
            - { property: 'imageFile', type: 'vich_image' }
            - { property: 'images', type: 'collection', type_options: {entry_type: 'App\Form\ImagesType', by_reference: false} }
            - name

      SubCategory:
        class: App\Entity\SubCategory
        list:
          fields:
            - id
            - name
            - category
            - { property: 'image', type: 'image', base_path: '%uploads_path%'}
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        show:
          fields:
            - { property: 'image', type: 'image', base_path: '%uploads_path%' }
        form:
          fields:
            - { property: 'imageFile', type: 'vich_image' }
            - name
            - category

      SubCategory2:
        class: App\Entity\SubCategory2
        list:
          fields:
            - id
            - name
            - subCategory
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        form:
          fields:
            - name
            - subCategory

      Order:
        class: App\Entity\Order
        disabled_actions: ['new','edit','delete']
        list:
          fields:
            - id
            - reference
            - date
            - status
            - shipping_date
            - shipping_methode
            - orderProducts
            - user

      Product:
        class: App\Entity\Product
        list:
          fields:
            - id
            - name
            - price
            - description
            #- { property: 'images', type: 'image', base_path: '%uploads_path%' }
            - status
            - subCategory
            #- tags
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        show:
          fields:
            - { property: 'images', type: 'image', base_path: '%uploads_path%' }
        form:
          fields:
            - { property: 'images', type: 'collection', type_options: {entry_type: 'App\Form\ImagesType', by_reference: false} }
            - name
            - price
            - { property: 'description', type: 'fos_ckeditor'}
            - subCategory
            - subCategory2
            - { property: 'tags', type_options: { by_reference: false }}

      Size:
        class: App\Entity\Size
        list:
          fields:
            - id
            - name
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        form:
          fields:
            - name

      Stock:
        class: App\Entity\Stock
        list:
          fields:
            - id
            - quantity
            - minimum
            - product
            - size
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}

      ShippingMethod:
        class: App\Entity\ShippingMethod
        list:
          fields:
            - id
            - type
            - price
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        form:
          fields:
            - type
            - price

      Tag:
        class: App\Entity\Tag
        list:
          fields:
            - id
            - name
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
        form:
          fields:
            - name

      User:
        class: App\Entity\User
        list:
          fields:
            - id
            - firstname
            - lastname
            - date_brith
            - email
            - phone
            - registration_date
            - is_verified
            - orders
            - addresses
          actions:
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
