vich_uploader:
    db_driver: orm

    mappings:
        product:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
        image:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
        banner:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
        category:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
        subCategory:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
